---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: end-of-file-fixer
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args:
          - --format=parsable
          - --strict
        exclude: user-data.yaml
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.1
    hooks:
      - id: yamlfmt
        args:
          - --mapping=2
          - --sequence=4
          - --offset=2
          # Match .yamllint.yaml; we don't care about line-length.
          - --width=1200
        exclude: user-data.yaml
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.8.4
    hooks:
      - id: gitleaks
  # Only running manual due to clang-format still misaligning some code.
  # Use this to run it: pre-commit run --all-files --hook-stage manual
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.5
    hooks:
      - id: clang-format
        files: \.(c|cc|cpp|h|hpp|cxx|hxx|glsl)$
        types_or: [text]
        stages: [manual]
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.2.1
    hooks:
      - id: editorconfig-checker
